### ISSUE TITLE
Valuerror encountered in running make_dataset

### ISSUE THREAD

**Issue by Leungfranklin** [leeyeehoo/CSRNet-pytorch#16]
When I run the make_dataset, I encounter the error "ValueError: not enough values to unpack (expected 2, got 0)" as below

ValueError                                Traceback (most recent call last)
<ipython-input-11-2f11adf9ee13> in <module>()
      8         if int(gt[i][1])<img.shape[0] and int(gt[i][0])<img.shape[1]:
      9             k[int(gt[i][1]),int(gt[i][0])]=1
---> 10     k = gaussian_filter_density(k)
     11     with h5py.File(img_path.replace('.jpg','.h5').replace('images','ground_truth'), 'w') as hf:
     12             hf['density'] = k

<ipython-input-5-a81722601ed4> in gaussian_filter_density(gt)
     10     leafsize = 2048
     11     # build kdtree
---> 12     tree = scipy.spatial.KDTree(pts.copy(), leafsize=leafsize)
     13     # query kdtree
     14     distances, locations = tree.query(pts, k=4)

~/anaconda3/lib/python3.6/site-packages/scipy/spatial/kdtree.py in __init__(self, data, leafsize)
    233     def __init__(self, data, leafsize=10):
    234         self.data = np.asarray(data)
--> 235         self.n, self.m = np.shape(self.data)
    236         self.leafsize = int(leafsize)
    237         if self.leafsize < 1:

ValueError: not enough values to unpack (expected 2, got 0)

**Comment by MSoulPlayer** [comment]
@Leungfranklin When using python 3.6, 'zip()'returns a zip object and in python 2.7 'zip()' returns a list, so this line should be replaced.
`pts = np.array(zip(np.nonzero(gt)[1], np.nonzero(gt)[0]))`
to
`pts = np.array(list(zip(np.nonzero(gt)[1], np.nonzero(gt)[0])))`

**Comment by Leungfranklin** [comment]
@MSoulPlayer    Thanks, the issue has been resolved.
