### ISSUE TITLE
How to generate the density map from the output of model

### ISSUE THREAD

**Issue by neverland0621** [leeyeehoo/CSRNet-pytorch#30]
Thank you for releasing the code.
I have some questions about the source code.
1.How to generate the density map from the output of model?I didn't get the desity map from the output of the model when i run the val.ipython but only the groudtruth of density map.or ,how to transform the output of the model to densoty map?
2. I found that the sum of the density map from groundtruth is not same as the groundtruth  count number of shanghaitech dataset in .mat file.even worse ,they are very different just as the picture.if the sum of groundtruth is far from the real count number ,what does the meaning of calculating the error of it. 
number output  groundtruth
1 218.73355 265.32138
2 242.14491 232.52945
3 113.73707 65.99532
4 371.46692 372.23004
5 432.0569 306.81796
6 144.08446 190.22192
7 269.57242 269.53113
8 565.20056 565.5759
9 235.49048 307.76044
10 507.46124 510.92313
11 297.7716 298.135
12 317.20828 493.84286
13 665.5448 580.9203
14 536.8564 468.91245
15 189.81647 241.52519
16 558.702 583.2348
17 102.62774 95.6099
18 401.4803 376.6646
19 244.39113 211.23973
20 343.18445 373.51428
we can find that the difference of two count numbers from one picture.they are the count number from .mat file (.mat  image_info  number)and the count number from sum of generated density map.we can get the count number from sum of generated density map of the fist image in shanghaitech A from the data above ,it equals 265.32, however,the count number from .mat file of this image is 172. And not only this image,most of the data have the same problem.
here is my code:
mae = 0
for i in xrange(len(img_paths)):
    img = 255.0 * F.to_tensor(Image.open(img_paths[i]).convert('RGB'))
    img[0,:,:]=img[0,:,:]-92.8207477031
    img[1,:,:]=img[1,:,:]-95.2757037428
    img[2,:,:]=img[2,:,:]-104.877445883
    img = img.cuda()
    img = transform(Image.open(img_paths[i]).convert('RGB')).cuda()
    gt_file = h5py.File(img_paths[i].replace('.jpg','.h5').replace('images','ground_truth'),'r')
    groundtruth = np.asarray(gt_file['density'])
    output = model(img.unsqueeze(0))
    print i+1,output.detach().cpu().sum().numpy(),np.sum(groundtruth)
    #print mse
I will appreciate the help if anyone has idea of the problem, thank you!

**Comment by aditya-malte** [comment]
Hello, 
The output of the model can be converted to a heatmap by using matplotlib like this:

from matplotlib import cm
plt.imshow(output , cmap = cm.jet )

This maps the raw [0,1] to H->[240, 0]. (H being hue from HSV).

PS. For your second doubt: The count values might vary a tiny bit due to the gaussian blur(this is because only an infinitely large kernel can approximate the gaussian blur accurately)

Thanks

**Comment by neverland0621** [comment]
@aditya-malte
Thank you for your help!
I have generated the density map by your method.

Could you give me more detail information of my second doubt?  I can understand that  the count values might vary due to the gaussian blur,but I can't understand the count vary too much.

just like the data below ,the first column is the serial number  of the first ten images in Shanghaitech,the second column is the count of groundtruth(caculated by np.sum(groundtruth)) ,and the third column is the real groundtruth in the mat file from databese(from  .mat   image_info   number).   I have shown the relevant code above.

We can obverse that they are very different , especially the 2,5,8 case. If the groundtruth we generated has such hign error,how can we ensure taht the model we train by this groudtruth has high accuracy?

1        265         172
2        233         1111
3         66          302
4        372         170
5        307         819
6        190         361
7        270         568
8        566        1326
9        308         371
10      511         502

Thank you !

**Comment by neverland0621** [comment]
@aditya-malte
Thank you for your help!  The  problems have been solved.^_^

**Comment by wait1988** [comment]
Can you tell me how to solve it?

**Comment by aditya-malte** [comment]
@neverland0621 you're welcome

**Comment by aditya-malte** [comment]
@wait1988 you could use the code I have shown in my previous comment

**Comment by SJLNNU** [comment]
@aditya-malte  Could you tell me more about the heatmap  . I use firest test imagein  shanghai tech dataset .The output (output.detach().cpu().numpy())'s size is 11264,but the input image size is 1024*704 ,I can't get a heatmap for each pix in the input image.  Plz help me out.

**Comment by aditya-malte** [comment]
Hi SJLNNU,
I didn't understand what you mean to say exactly. Check my answers to say if they help.
Regards,
Aditya Malte

**Comment by SJLNNU** [comment]
@aditya-malte   Hi ,sorry for my  statement .  There is the thing :  I Add "plt.imshow(output.detach().cpu().numpy()  , cmap = cm.jet )”   at the end of code just like you said . But it returns
________________________________________________
Traceback (most recent call last):
  File "G:/CrowdDetection/CSRNet-pytorch-master/val.py", line 64, in <module>
    plt.imshow(output.detach().cpu().numpy()  , cmap = cm.jet )
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\pyplot.py", line 3205, in imshow
    **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\axes\_axes.py", line 5487, in imshow
    im.set_data(X)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\image.py", line 653, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data
_______________________________________________________
The Size of 'output.detach().cpu().numpy()' is not enough to reshape into  input image size.
What should I do to out put the heat Image?
Thank you for your time .

**Comment by aditya-malte** [comment]
Hello SJLNNU,
The problem appears to be from some other part of your code then, because I haven't faced such an issue.

Best,
Aditya Malte

**Comment by xincmm** [comment]
@SJLNNU, @aditya-malte 
I also encountered the same problem. I solved it. the output is a tensor, tensor and PIL can be converted。in the val.py add the following cod:
```
from torchvision import transforms
import matplotlib.pyplot as plt

loader = transforms.Compose([
    transforms.ToTensor()])  

unloader = transforms.ToPILImage()

def imshow(tensor, title=None):
    image = tensor.cpu().clone()  # we clone the tensor to not do changes on it
    image = image.squeeze(0)  # remove the fake batch dimension
    image = unloader(image)
    plt.imshow(image)
    if title is not None:
        plt.title(title)
    plt.pause(0.001)  # pause a bit so that plots are updated
```

Now use can use imshow like this:
`imshow(output)`
result:
![result.png](https://i.loli.net/2019/05/08/5cd22e8628ea5.png)

And then，you can also save tensor or PIL to image by use `torchvision.utils.save_image`
reference: [https://pytorch.org/docs/stable/torchvision/utils.html](https://pytorch.org/docs/stable/torchvision/utils.html)

**Comment by SJLNNU** [comment]
> @SJLNNU, @aditya-malte
> I also encountered the same problem. I solved it. the output is a tensor, tensor and PIL can be converted。in the val.py add the following cod:
> 
> ```
> from torchvision import transforms
> import matplotlib.pyplot as plt
> 
> loader = transforms.Compose([
>     transforms.ToTensor()])  
> 
> unloader = transforms.ToPILImage()
> 
> def imshow(tensor, title=None):
>     image = tensor.cpu().clone()  # we clone the tensor to not do changes on it
>     image = image.squeeze(0)  # remove the fake batch dimension
>     image = unloader(image)
>     plt.imshow(image)
>     if title is not None:
>         plt.title(title)
>     plt.pause(0.001)  # pause a bit so that plots are updated
> ```
> 
> Now use can use imshow like this:
> `imshow(output)`
> result:
> ![result.png](https://camo.githubusercontent.com/2378f17ff4f43805a09c28c5f48c5567d45ecd39/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30352f30382f356364323265383632386561352e706e67)
> 
> And then，you can also save tensor or PIL to image by use `torchvision.utils.save_image`
> referencer: https://pytorch.org/docs/stable/torchvision/utils.html

Thanks men ,I solved too.

**Comment by hiramustafa77** [comment]
> Hello, The output of the model can be converted to a heatmap by using matplotlib like this:
> 
> from matplotlib import cm plt.imshow(output , cmap = cm.jet )
> 
> This maps the raw [0,1] to H->[240, 0]. (H being hue from HSV).
> 
> PS. For your second doubt: The count values might vary a tiny bit due to the gaussian blur(this is because only an infinitely large kernel can approximate the gaussian blur accurately)
> 
> Thanks

Thank you so much for this help.
