### ISSUE TITLE
python3下使用报错

### ISSUE THREAD

**Issue by wait1988** [leeyeehoo/CSRNet-pytorch#39]
self.frontend.state_dict().items()[i][1].data[:] = mod.state_dict().items()[i][1].data[:]
TypeError: 'odict_items' object does not support indexing

有大神知道该怎么改吗？

**Comment by WhuRan** [comment]
items1 = list(self.frontend.state_dict().items())
items2 = list(mod.state_dict().items())
items1[i][1].data[:] = items2[i][1].data[:]

**Comment by wait1988** [comment]
Thks
