### ISSUE TITLE
AttributeError: module 'torch.nn.init' has no attribute 'normal_'

### ISSUE THREAD

**Issue by hipal3101** [leeyeehoo/CSRNet-pytorch#45]
in val.ipynb file while executing 
model = CSRNet()
i got this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-a01e0b93a8e4> in <module>()
----> 1 model = CSRNet()

~\CSRNet-pytorch-master\model.py in __init__(self, load_weights)
     15         if not load_weights:
     16             mod = models.vgg16(pretrained = True)
---> 17             self._initialize_weights()
     18             for i in xrange(len(self.frontend.state_dict().items())):
     19                 self.frontend.state_dict().items()[i][1].data[:] = mod.state_dict().items()[i][1].data[:]

~\CSRNet-pytorch-master\model.py in _initialize_weights(self)
     26         for m in self.modules():
     27             if isinstance(m, nn.Conv2d):
---> 28                 nn.init.normal_(m.weight, std=0.01)
     29                 if m.bias is not None:
     30                     nn.init.constant_(m.bias, 0)

AttributeError: module 'torch.nn.init' has no attribute 'normal_'

**Comment by zly9120** [comment]
have you solved this problem?

**Comment by hipal3101** [comment]
> have you solved this problem?

Actually I don't remember now exactly.
But Try running it on Google colab with GPU.
